% high oscillated denoising
% See Experiment 3

clear all, close all
N = 500; L = N; LL = 100;
ff = -1:0.01:1; [f,w,v] = jacpts(N+1,-.5,-.5);
GG =  airy(40*ff); G= airy(40*f);
[YY,NOISE] = noisegen(GG,10); [Y,NOISE] = noisegen(G,12);
lambda = [0 10^(-1) 10^(-2) 10^(-5)];
for l = 0:1:L
    mu(l+1) = 1/Filter(L,l);
end
mu = mu';
for l = 0:L
    for j = 0:N
        A(j+1,l+1) = cos(l*acos(f(j+1)))/sqrt(pi/2);
    end
end
A(:,1) = A(:,1)/sqrt(2);

% plot
Color = [215,25,28;
253,174,97;
254,204,92;
171,217,233;
44,123,182]/255;

fontsize_baseline = 10;
subplot(4,4,1), plot(ff,GG), xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Original function','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off'),
subplot(4,4,2), plot(ff,YY), xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Noisy function','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off'),

p2 = bary(ff, Y/(1+lambda(1)*mu(1)^2),f, v);
subplot(4,4,5),plot(ff,p2),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('$\lambda=0$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off'),
subplot(4,4,6), plot(ff,abs(GG-p2)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error', 'interpreter','latex','fontsize', fontsize_baseline),...
    title('Error, $\lambda=0$','interpreter','latex'),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off'),

p21 = bary(ff, Y/(1+lambda(2)*mu(1)^2),f, v);
p22 = bary(ff, Y/(1+lambda(3)*mu(1)^2),f, v);
p23 = bary(ff, Y/(1+lambda(4)*mu(1)^2),f, v);
a1 = zeros(L+1,1); a2 = zeros(L+1,1); a3 = zeros(L+1,1);
Ax = A'*(w'.*Y);
for k = 2:4
for i = 0:L
    if 2*Ax(i+1)>lambda(k)*mu(i+1)
        a(i+1,k-1) = -lambda(k)*mu(i+1)/2;
    elseif 2*Ax(i+1)<-lambda(k)*mu(i+1)
        a(i+1,k-1) = lambda(k)*mu(i+1)/2;
    else
        a(i+1,k-1) = -Ax(i+1);
    end
end
end
AA1 = a(:,1)'*A'; AA2 = a(:,2)'*A'; AA3 = a(:,3)'*A';
p11 = bary(ff, Y+AA1',f, v);
p12 = bary(ff, Y+AA2',f, v);
p13 = bary(ff, Y+AA3',f, v);
subplot(4,4,9),plot(ff,p21),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('$\ell_2$ model, $\lambda=10^{-1}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,10),plot(ff,abs(GG-p21)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error, $\ell_2$ model, $\lambda=10^{-1}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off')
subplot(4,4,13),plot(ff,p11),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$', 'interpreter','latex','fontsize', fontsize_baseline),...
    title('$\ell_1$ model, $\lambda=10^{-1}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,14),plot(ff,abs(GG-p11)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error: $\ell_1$ model, $\lambda=10^{-1}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off')
subplot(4,4,3),plot(ff,p22),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('$\ell_2$ model, $\lambda=10^{-2}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,4),plot(ff,abs(GG-p22)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error, $\ell_2$ model, $\lambda=10^{-2}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off')
subplot(4,4,7),plot(ff,p12),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$', 'interpreter','latex','fontsize', fontsize_baseline),...
    title('$\ell_1$ model, $\lambda=10^{-2}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,8), plot(ff,abs(GG-p12)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error: $\ell_1$ model, $\lambda=10^{-2}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]), set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,11),plot(ff,p23),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('$\ell_2$ model, $\lambda=10^{-5}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline), set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,12), plot(ff,abs(GG-p23)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error, $\ell_2$ model, $\lambda=10^{-5}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off')
subplot(4,4,15),plot(ff,p13),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('$f(x)$', 'interpreter','latex','fontsize', fontsize_baseline),...
    title('$\ell_1$ model, $\lambda=10^{-5}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,-.6,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'), set(gca, 'YMinorGrid', 'off'),
subplot(4,4,16), plot(ff,abs(GG-p13)),xlabel('$x$','interpreter','latex', 'fontsize', fontsize_baseline),ylabel('Absolute error','interpreter','latex', 'fontsize', fontsize_baseline),...
    title('Error: $\ell_1$ model, $\lambda=10^{-5}$','interpreter','latex', 'fontsize', fontsize_baseline),grid on,box on,...
    axis([-1,1,0,.6]),set(gca, 'fontsize', fontsize_baseline),set(gca, 'XMinorGrid', 'off'),set(gca, 'YMinorGrid', 'off')
